# Generated by Django 4.1.3 on 2022-11-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_released', models.DateField(verbose_name='date released')),
                ('likes', models.IntegerField(default=0)),
                ('artise_id', models.CharField(max_length=50)),
                ('Artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songify.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('song_id', models.CharField(max_length=50)),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songify.song')),
            ],
        ),
    ]
